### ISSUE TITLE
[Bug]: the programming for the top of the window in dot browser is incorrect

### ISSUE THREAD

**Issue by cheqhz** [dothq/browser-desktop#85] opened 2022-05-25 00:24 UTC
### Preflight Checklist

- [X] I have checked the [issue tracker](https://github.com/dothq/browser/issues) for issues that may be similar to mine.
- [X] I have checked whether this issue can be reproduced on another setup (e.g. other operating system or browser version/channel)
- [X] I have checked that the title is not empty.

### Description

the programming for the top of the window in dot browser is incorrect

### Steps to Reproduce

make a new update in 2022 and fix the the top of the window

### Actual result

![Dot Browser 5_24_2022 5_22_40 PM](https://user-images.githubusercontent.com/106205890/170152863-46978a12-8573-44bc-8b07-6839fde0e167.png)

look at the top

### Expected result

![Dot Browser 5_24_2022 5_24_07 PM](https://user-images.githubusercontent.com/106205890/170152958-237a08d5-9908-4799-aa75-db72c73c1387.png)

look at the top

### Browser version

Nightly v87.0

### Browser build date

2021-07-24

### Browser channel

Nightly

### Other information

that is it

**Comment by kierandrewett** [comment] 2022-05-25 14:24
Duplicate of dothq/browser-desktop#84

**Closed as completed by kierandrewett** 2022-05-25 14:24 UTC
Labels: bug
