### ISSUE TITLE
Title bar is cut off

### ISSUE THREAD

**Issue by garyteofanus** [dothq/browser-desktop#93] opened 2021-09-19 19:43 UTC
* [x] I have read the [Contributing Guidelines](https://github.com/dothq/browser/blob/main/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Component**

**Describe the bug**
The title bar is cut off on any window size (maximized or not maximized) and the close button position is a bit off. 

**To Reproduce**
1. Open dot browser
2. Open any site (or no site at all)

**Expected behavior**
The title bar is not cut off

**Screenshots**
Full screen
![image](https://user-images.githubusercontent.com/40825899/133940580-512fd8d2-cdee-41c9-af2e-801723a2d5b1.png)

Windowed
![image](https://user-images.githubusercontent.com/40825899/133940830-63b4668b-5a1c-4793-ba86-b98f4ede1c2d.png)

**System Information (please complete the following information):**
 - OS: Arch Linux
 - Version: Rolling Release

**Dot Browser Information (please complete the following information):**
 - Version: Nightly v87.0 - 2021-07-24
 - Site you were on before the bug appeared: Any site

**Additional context**
-

**Comment by kierandrewett** [comment] 2021-09-19 19:48
Duplicate of dothq/browser-desktop#101 dothq/browser-desktop#266 dothq/browser-desktop#89 dothq/browser-desktop#260

**Closed as completed by kierandrewett** 2021-09-19 19:48 UTC
