### ISSUE TITLE
[Bug]: Top of screen chopped off

### ISSUE THREAD

**Issue by gluester** [dothq/browser-desktop#267] opened 2022-09-16 20:09 UTC
When I open Dot and set maximize it, the top of the app is cut off.
![image](https://user-images.githubusercontent.com/59670472/190724495-c4b113bd-165d-4d64-8143-6f9894b33343.png)

It's a little cut off, but fine when it isn't maximized:
![image](https://user-images.githubusercontent.com/59670472/190724603-95abbec1-8fa2-4cab-9961-0953de9f541e.png)

Thanks!

**Comment by kierandrewett** [comment] 2022-09-16 20:53
Duplicate of #93

**Closed as completed by kierandrewett** 2022-09-16 20:53 UTC
