### ISSUE TITLE
UI bugged

### ISSUE THREAD

**Issue by thedatabug** [dothq/browser-desktop#87] opened 2021-09-20 19:12 UTC
Im running Dot on Windows 10. My UI is bugged and the buttons are cut off at the top. Here is a screenshot https://photos.app.goo.gl/3VDNRWSyNABSXBGPA

**Comment by kierandrewett** [comment] 2021-09-20 19:13
Duplicate of dothq/browser-desktop#84

**Closed as completed by kierandrewett** 2021-09-20 19:13 UTC
