### ISSUE TITLE
[Bug]: url bar is cut off

### ISSUE THREAD

**Issue by Connor0517** [dothq/browser-desktop#86] opened 2021-12-29 04:02 UTC
### Preflight Checklist

- [X] I have checked the [issue tracker](https://github.com/dothq/browser/issues) for issues that may be similar to mine.
- [X] I have checked whether this issue can be reproduced on another setup (e.g. other operating system or browser version/channel)
- [X] I have checked that the title is not empty.

### Description

url bar is cut off at top of screen

### Steps to Reproduce

run browser

### Actual result

![Uploading Screenshot (3).png…]()

### Expected result

the url bar shouldn't be cut off.

### Browser version

0.3.0 (64-bit)

### Browser build date

2021-07-24

### Browser channel

Nightly

**Comment by kierandrewett** [comment] 2021-12-29 11:31
Duplicate of dothq/browser-desktop#84

**Closed as completed** 2021-12-29 11:31 UTC
Labels: bug
