### ISSUE TITLE
Odd blur behaviour when trying to close a tab.

### ISSUE THREAD

**Issue by Alex-Programs** [dothq/browser-desktop#100] opened 2021-09-27 18:57 UTC
* [x] I have read the [Contributing Guidelines](https://github.com/dothq/browser/blob/main/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Describe the bug**
When I try to close a tab via moving my cursor to the cross button and clicking it, the tab has a short delay (~.2s) before a blurry box appears over it.

It happens instantaneously if I click.

I cannot click through the blur to close the tab; doing so just shows a error in the command line output:
```
00:16:16 JavaScript error: chrome://dot/content/build/browser.js, line 2615: TypeError: event is undefined
00:16:16 JavaScript error: chrome://dot/content/build/browser.js, line 2615: TypeError: event is undefined
```

ctrl+w to close the tab still works fine.

**To Reproduce**
1. Open a tab
2. Hover over tab in the tab bar
3. Observe

**Expected behavior**
There should be no blurring and the tab should close when the button is clicked.

**Screenshots**
![image](https://user-images.githubusercontent.com/40502404/134968170-f705cf70-8ce8-4ffb-8928-2f97e25b3309.png)
![image](https://user-images.githubusercontent.com/40502404/134968139-8d6e17d4-1ecb-47c4-9cfa-f6e35b79bcc1.png)

**System Information (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS

**Dot Browser Information (please complete the following information):**
 - Version: Latest on Git.

**Comment by trickypr** [comment] 2021-09-28 04:04
Note for devs: this is caused by the tab preview being pain

**Comment by trickypr** [comment] 2021-09-28 05:07
I think I have fixed this, although tab previews are still not great, so I am going to close this issue

**Closed as completed by trickypr** 2021-09-28 05:07 UTC
