### ISSUE TITLE
Incorrect Bar Display on Windows

### ISSUE THREAD

**Issue by ToastcodeDev** [dothq/browser-desktop#295] opened 2023-07-05 22:25 UTC
I am using dot from windows but it has a display problem with the top bar.
![Captura de pantalla 2023-07-05 182509](https://github.com/dothq/browser-desktop/assets/67870123/dbea2f8b-8adb-41bf-9a32-ebe493eef2ab)

**Comment by kierandrewett** [comment] 2023-07-05 22:28
Duplicate of #93

**Closed as not planned** 2023-07-05 22:28 UTC
