### ISSUE TITLE
Cut window title on Manjaro KDE

### ISSUE THREAD

**Issue by v1rtl** [dothq/browser-desktop#92] opened 2021-09-19 21:29 UTC
* [x] I have read the [Contributing Guidelines](https://github.com/dothq/browser/blob/main/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Component**

Desktop browser

**Describe the bug**

Window title gets cut on Manjaro Linux KDE Edition with Krohnkite plugin. None of the apps I use (incl. Firefox) have this issue so most likely it's a Dot issue.

**To Reproduce**
1. Install Manjaro KDE Edition
2. Install Krohnkite tiling KWin script
3. Open Dot
4. See window title get cut

**Expected behavior**

It should render as any other desktop app.

**Screenshots**

![image](https://user-images.githubusercontent.com/35937217/133943513-d3f3cadd-6000-4bb6-9384-e0ca33b8ee8b.png)

**System Information:**
 - OS: Manjaro Linux KDE Edition
 - Version: Kernel 5.10.63

**Dot Browser Information:**
 - Version: 87
 - Site you were on before the bug appeared: homepage

**Additional context**

**Comment by kierandrewett** [comment] 2021-09-19 21:32
Duplicate of dothq/browser-desktop#101 dothq/browser-desktop#266 dothq/browser-desktop#89 dothq/browser-desktop#260 dothq/browser-desktop#93

**Closed as completed by kierandrewett** 2021-09-19 21:32 UTC
